# docker-compose.override.yml
# Local development overrides (not committed to production)
# Place this file in .gitignore for team-specific customization

services:
  cardactions-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBus__UseInMemory=true  # Force in-memory for local dev
      - Serilog__MinimumLevel__Default=Debug
    ports:
      - "49510:80"  # Match launchSettings.json ports
      - "49511:443"
    volumes:
      - ./logs:/app/logs  # Mount logs for easy access

  # RabbitMQ service (optional, only if testing RabbitMQ locally)
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: cardactions-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=cardactions
      - RABBITMQ_DEFAULT_PASS=devpassword
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq-data-dev:/var/lib/rabbitmq
    profiles:
      - rabbitmq  # Only start when explicitly requested

volumes:
  rabbitmq-data-dev: