version: '3.8'

services:
  cardactions-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBus__Provider=InMemory  # Changed from UseInMemory (deprecated)
      - Serilog__MinimumLevel__Default=Debug
    ports:
      - "49510:80"
      - "49511:443"
    volumes:
      - ./logs:/app/logs

  # RabbitMQ - starts only with --profile rabbitmq
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: cardactions-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=cardactions
      - RABBITMQ_DEFAULT_PASS=devpassword
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq-data-dev:/var/lib/rabbitmq
    profiles:
      - rabbitmq

  # IBM MQ - starts only with --profile ibmmq
  ibmmq:
    image: ibmcom/mq:latest
    container_name: cardactions-ibmmq-dev
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
      MQ_ADMIN_PASSWORD: passw0rd
      MQ_ENABLE_METRICS: "true"
      # Dev-specific: disable authentication for easier testing
      MQ_DEV: "true"
    volumes:
      - ibmmq-data-dev:/mnt/mqm
    profiles:
      - ibmmq

volumes:
  rabbitmq-data-dev:
  ibmmq-data-dev: